title: "Lukas Cha"
author: "Lukas Cha"
description: "Technical University of Munich"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", file: "cv_cha_2024.pdf"}
  - {title: "Lab", url: "https://eng.ox.ac.uk/hbl/"}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/lukascha/"}
  - {title: Google Scholar, icon: google-scholar, url: "https://scholar.google.com/citations?user=dDUvyf8AAAAJ&hl=en"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/lukas_cha"}
  - {title: Mail, icon: envelope, url: "mailto:lukascha0316@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/LukasCha"}
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/channel/UCKXeSlaEijmvHt0DjCgbUpA"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
